<?php
/**
*
* gallery [Dutch]
*
* @package phpBB Gallery
* @version $Id$
* @copyright (c) 2007 nickvergessen nickvergessen@gmx.de http://www.flying-bits.org
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
* [Dutch] translated by Dutch Translators (https://github.com/dutch-translators)
*
**/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

$lang = array_merge($lang, array(
	'ADD_UPLOAD_FIELD'				=> 'Voeg meer upload velden toe',
	'ALBUM'							=> 'Album',
	'ALBUM_IS_CATEGORY'				=> 'Het album waar je heen gegaan bent is een categoriealbum..<br />Je kan niet uploaden naar categorieën.',
	'ALBUM_LOCKED'					=> 'Gesloten',
	'ALBUM_NAME'					=> 'Albumnaam',
	'ALBUM_NOT_EXIST'				=> 'Dit album bestaat niet',
	'ALBUM_PERMISSIONS'				=> 'Album Permissies',
	'ALBUM_REACHED_QUOTA'			=> 'Dit album heeft het aantal afbeeldingen dat geupload mag worden bereikt, je kan geen nieuwe afbeeldingen uploaden.<br />Neem contact op met de beheerder voor meer informatie.',
	'ALBUM_UPLOAD_NEED_APPROVAL'		=> 'Je afbeeldingen zijn succesvol geüpload.<br /><br />Je afbeeldingen moeten eerst goedgekeurd worden door een beheerder of moderator voordat deze zichtbaar zijn voor het publiek.',
	'ALBUM_UPLOAD_NEED_APPROVAL_ERROR'	=> 'Sommige afbeeldingen zijn succesvol geüpload.<br /><br />Je afbeeldingen moeten eerst goedgekeurd worden door een beheerder of moderator voordat deze zichtbaar zijn voor het publiek.<br /><br /><p class="error">%s</p>',
	'ALBUM_UPLOAD_SUCCESSFUL'		=> 'Je afbeeldingen zijn succesvol geüpload .',
	'ALBUM_UPLOAD_SUCCESSFUL_ERROR'	=> 'Sommige afbeeldingen zijn succesvol geüpload.<br /><br /><span class="error">%s</span>',
	'ALBUMS_MARKED'					=> 'Alle albums zijn als gelezen gemarkeerd.',
	'ALL'							=> 'Alle',
	'ALL_IMAGES'					=> 'Alle afbeeldingen',
	'ALLOW_COMMENTS'				=> 'Reacties op deze afbeelding toestaan.',
	'ALLOW_COMMENTS_ARY'			=> array(
		0	=> 'Reacties op deze afbeelding toestaan.',
		2	=> 'Reacties op deze afbeeldingen toestaan.',
	),
	'ALLOWED_FILETYPES'				=> 'Toegestane bestandsformaten',
	'APPROVE'						=> 'Goedkeuren',
	'APPROVE_IMAGE'					=> 'Afbeelding goedkeuren',

	//@todo
	'ALBUM_COMMENT_CAN'			=> 'Je <strong>kan</strong> reageren op afbeeldingen in dit album',
	'ALBUM_COMMENT_CANNOT'		=> 'Je <strong>kan niet</strong> reageren op afbeeldingen in dit album',
	'ALBUM_DELETE_CAN'			=> 'Je <strong>kan</strong> je eigen afbeeldingen uit dit album verwijderen',
	'ALBUM_DELETE_CANNOT'		=> 'Je kan je eigen afbeeldingen uit dit album <strong>niet</strong> verwijderen',
	'ALBUM_EDIT_CAN'			=> 'Je <strong>kan</strong> je eigen afbeeldingen uit dit album wijzigen',
	'ALBUM_EDIT_CANNOT'			=> 'Je kan je eigen afbeeldingen uit dit album <strong>niet</strong> wijzigen',
	'ALBUM_RATE_CAN'			=> 'Je <strong>kan</strong> afbeeldingen uit dit album beoordelen',
	'ALBUM_RATE_CANNOT'			=> 'Je kan afbeeldingen uit dit album <strong>niet</strong> beoordelen',
	'ALBUM_UPLOAD_CAN'			=> 'Je <strong>kan</strong> niewe afbeeldingen uploaden naar dit album',
	'ALBUM_UPLOAD_CANNOT'		=> 'Je <strong>kan geen</strong> niewe afbeeldingen uploaden naar dit album',
	'ALBUM_VIEW_CAN'			=> 'Je <strong>kan</strong> afbeeldingen uit dit album zien',
	'ALBUM_VIEW_CANNOT'			=> 'Je kan de afbeeldingen uit dit album <strong>niet</strong> zien',

	'BAD_UPLOAD_FILE_SIZE'			=> 'Je geüploade bestand is te groot',
	'BBCODES'						=> 'BBCodes',
	'BROWSING_ALBUM'				=> 'Gebruikers die dit album bekijken: %1$s',
	'BROWSING_ALBUM_GUEST'			=> 'Gebruikers die dit album bekijken: %1$s en %2$d gast',
	'BROWSING_ALBUM_GUESTS'			=> 'Gebruikers die dit album bekijken: %1$s en %2$d gasten',

	'CHANGE_AUTHOR'					=> 'Wijzig auteur',
	'CHANGE_IMAGE_STATUS'			=> 'Verander afbeeldingsstatus',
	'CHARACTERS'					=> 'karakters',
	'CLICK_RETURN_ALBUM'			=> 'Klik %shier%s om terug te gaan naar het album',
	'CLICK_RETURN_IMAGE'			=> 'Klik %shier%s om terug te gaan naar de afbeelding',
	'CLICK_RETURN_INDEX'			=> 'Klik %shier%s om terug te gaan naar de albumindex',
	'COMMENT'						=> 'Reactie',
	'COMMENT_IMAGE'					=> 'Reageren op een afbeelding in het album %s',
	'COMMENT_LENGTH'				=> 'Je kan hier een reactie invoeren, deze mag niet meer dan <strong>%d</strong> karakters bevatten.',
	'COMMENT_ON'					=> 'Reactie op',
	'COMMENT_STORED'				=> 'Je reactie is succesvol opgeslagen.',
	'COMMENT_TOO_LONG'				=> 'Je reactie is te lang.',
	'COMMENTS'						=> 'Reacties',
	'CONTEST_COMMENTS_STARTS'		=> 'Reacties op afbeeldingen in deze wedstrijd zijn toegestaan vanaf %s.',
	'CONTEST_ENDED'					=> 'Deze wedstrijd is geëindigd op %s.',
	'CONTEST_ENDS'					=> 'Deze wedstrijd eindigt op %s.',
	'CONTEST_RATING_STARTED'		=> 'De beoordelingsronde voor deze wedstrijd is begonnen op %s.',
	'CONTEST_RATING_STARTS'			=> 'De beoordelingsronde voor deze wedstrijd begint op %s.',
	'CONTEST_RATING_ENDED'			=> 'De beoordelingsronde voor deze wedstrijd is geëindigd op %s.',
	'CONTEST_RATING_HIDDEN'			=> 'verborgen',
	'CONTEST_RESULT'				=> 'Wedstrijd',
	'CONTEST_RESULT_1'				=> 'Winnaar',
	'CONTEST_RESULT_2'				=> 'Tweede',
	'CONTEST_RESULT_3'				=> 'Derde',
	'CONTEST_RESULT_HIDDEN'			=> 'De beoordelingen van deze afbeeldingen zijn verborgen tot de wedstrijd eindigt op %s.',
	'CONTEST_STARTED'				=> 'Deze wedstrijd is begonnen op %s.',
	'CONTEST_STARTS'				=> 'Deze wedstrijd begint op %s.',
	'CONTEST_USERNAME'				=> '<strong>Wedstrijd</strong>',
	'CONTEST_USERNAME_LONG'			=> '<strong>Wedstrijd</strong> » De gebruikersnaam is verborgen tot de wedsteijd eindigt op %s.',
	'CONTEST_IMAGE_DESC'			=> '<strong>Wedstrijd</strong> » De afbeeldingsomschrijving is verborgen tot de wedsteijd eindigt op %s.',
	'CONTEST_WINNERS_OF'			=> 'Wedstrijd winnaar van “%s“',
	'CONTINUE'						=> 'Doorgaan',

	'DATABASE_NOT_UPTODATE'			=> 'Je database heeft niet dezelfde versie als je bestanden. Update alstublieft je database.',
	'DELETE_COMMENT'				=> 'Verwijder reactie',
	'DELETE_COMMENT2'				=> 'Reactie verwijderen?',
	'DELETE_COMMENT2_CONFIRM'		=> 'Weet je zeker dat je deze reactie wilt verwijderen?',
	'DELETE_IMAGE'					=> 'Verwijder',
	'DELETE_IMAGE2'					=> 'Afbeelding verwijderen?',
	'DELETE_IMAGE2_CONFIRM'			=> 'Weet je zeker dat je de afbeelding wilt verwijderen?',
	'DELETED_COMMENT'				=> 'Reactie verwijderd',
	'DELETED_COMMENT_NOT'			=> 'Reactie niet verwijderd',
	'DELETED_IMAGE'					=> 'Afbeelding verwijderd',
	'DELETED_IMAGE_NOT'				=> 'Afbeelding niet verwijderd',
	'DESC_TOO_LONG'					=> 'Je omschrijving is te lang',
	'DESCRIPTION_LENGTH'			=> 'Je kan hier een omschrijving invoeren, deze mag niet meer dan <strong>%d</strong> karakters bevatten.',
	'DETAILS'						=> 'Details',
	'DONT_RATE_IMAGE'				=> 'Beoordeel afbeeldingen niet',

	'EDIT_COMMENT'					=> 'Wijzig reactie',
	'EDIT_IMAGE'					=> 'Wijzig',
	'EDITED_TIME_TOTAL'				=> 'Laatst gewijzigd door %s op %s;, %d keer totaal gewijzigd',
	'EDITED_TIMES_TOTAL'			=> 'Laatst gewijzigd door %s op %s;, %d keer totaal gewijzigd',

	'FILE'							=> 'Bestand',
	'FILE_SIZE'						=> 'Bestandsgrootte',
	'FILETYPE_MIMETYPE_MISMATCH'	=> 'Het bestandstype van “<strong>%1$s</strong>“ sluit niet aan bij het mime-type (%2$s).',
	'FILETYPES_GIF'					=> 'gif',
	'FILETYPES_JPG'					=> 'jpg',
	'FILETYPES_PNG'					=> 'png',
	'FILETYPES_ZIP'					=> 'zip',

	'GALLERY_IMAGE'					=> 'Afbeelding',
	'GALLERY_IMAGES'					=> 'Afbeeldingen',
	'GALLERY_VIEWS'					=> 'Weergaves',

	'IGNORE_NOTUPTODATE_MESSAGE'		=> 'Herinner mij over 7 dagen weer',
	'IMAGE_ALREADY_REPORTED'			=> 'Deze afbeelding is al gemeld.',
	'IMAGE_BBCODE'						=> 'Afbeelding BBCode',
	'IMAGE_COMMENTS_DISABLED'			=> 'Reacties zijn voor deze afbeelding uitgeschakeld.',
	'IMAGE_DAY'							=> '%.2f afbeeldingen per dag',
	'IMAGE_DESC'						=> 'Afbeelding omschrijving',
	'IMAGE_HEIGHT'						=> 'Afbeeldingshoogte',
	'IMAGE_INSERTED'					=> 'Afbeelding ingevoerd',
	'IMAGE_LOCKED'						=> 'Sorry, deze afbeelding is gesloten. Je kan geen reacties meer plaatsen op deze afbeelding.',
	'IMAGE_NAME'						=> 'Afbeeldingsnaam',
	'IMAGE_NOT_EXIST'					=> 'Deze afbeelding bestaat niet.',
	'IMAGE_PCT'							=> '%.2f%% van alle afbeeldingen',
	'IMAGE_STATUS'						=> 'Status',
	'IMAGE_URL'							=> 'Afbeeldingslink',
	'IMAGE_WIDTH'						=> 'Afbeeldingsbreedte',
	'IMAGES_REPORTED_SUCCESSFULLY'		=> 'Deze afbeelding is succesvol gemeld',
	'IMAGES_UPDATED_SUCCESSFULLY'		=> 'De afbeeldingsinformatie is succesvol bijgewerkt',
	'INSERT_IMAGE_POST'					=> 'Voeg afbeelding aan bericht toe',
	'INVALID_USERNAME'					=> 'Je gebruikersnaam is ongeldig',

	'LAST_COMMENT'					=> 'Laatste reactie',
	'LAST_IMAGE'					=> 'Laatste afbeelding',
	'LOGIN_EXPLAIN_UPLOAD'			=> 'Je moet geregistreerd en aangemeld zijn om afbeeldingen te kunnen uploaden in dit album.',

	'MARK_ALBUMS_READ'				=> 'Markeer albums als gelezen',
	'MAX_DIMENSIONS'				=> 'Maximale afmetingen',
	'MAX_FILE_SIZE'					=> 'Maximale bestandsgrootte (bytes)',
	'MAX_HEIGHT'					=> 'Maximale afbeeldinghoogte (beeldpunten)',
	'MAX_WIDTH'						=> 'Maximale afbeeldingbreedte (beeldpunten)',
	'MISSING_COMMENT'				=> 'No Message entered',
	'MISSING_IMAGE_NAME'			=> 'Je moet een naam opgeven bij het bewerken van een afbeelding.',
	'MISSING_MODE'					=> 'Geen modus geselecteerd',
	'MISSING_REPORT_REASON'			=> 'Je moet een reden opgeven, als je deze afbeelding wilt melden.',
	'MISSING_SLIDESHOW_PLUGIN'		=> 'Geen slideshow-plugin gevonden. Neem contact op met de forumbeheerder..',
	'MISSING_SUBMODE'				=> 'No submode selected',
	'MISSING_USERNAME'				=> 'Geen gebruikersnaam ingevoerd',
	'MOVE_TO_ALBUM'					=> 'Verplaats naar album',
	'MOVE_TO_PERSONAL'				=> 'Verplaats naar persoonlijk album',
	'MOVE_TO_PERSONAL_MOD'			=> 'When you select this option, the image is moved into the personal album of the user. If the user does not have one yet, it is created automatically.',
	'MOVE_TO_PERSONAL_EXPLAIN'		=> 'When you select this option, the image is moved into your personal album. If you do not have one yet, it is created automatically.',

	'NEW_COMMENT'					=> 'Nieuwe Reactie',
	'NEW_IMAGES'					=> 'Nieuwe afbeeldingen',
	'NEWEST_PGALLERY'				=> 'Our newest personal gallery %s',
	'NO_ALBUMS'						=> 'There are no albums in this gallery.',
	'NO_COMMENTS'					=> 'No comments yet',
	'NO_IMAGES'						=> 'No images',
	'NO_IMAGES_FOUND'				=> 'No images found.',
	'NO_NEW_IMAGES'					=> 'No new images',
	'NO_IMAGES_LONG'				=> 'There are no images in this album.',
	'NOT_ALLOWED_FILE_TYPE'			=> 'This file type is not allowed',
	'NOT_RATED'						=> 'not rated',

	'ORDER'							=> 'Order',
	'ORIG_FILENAME'					=> 'Take filename as imagename (the insert-field has no function)',
	'OUT_OF_RANGE_VALUE'			=> 'Value is out of range',
	'OWN_IMAGES'					=> 'Your Images',

	'PERCENT'						=> '%',
	'PERSONAL_ALBUMS'				=> 'Personal albums',
	'PIXELS'						=> 'pixels',
	'PLUGIN_CLASS_MISSING'			=> 'Gallery Plugin Error: Class “%s“ could not be found!',
	'POST_COMMENT'					=> 'Post a comment',
	'POST_COMMENT_RATE_IMAGE'		=> 'Post a comment and rate the image',
	'POSTER'						=> 'Poster',

	'QUOTA_REACHED'					=> 'The number of images you are allowed to upload has been reached.',
	'QUOTE_COMMENT'					=> 'Quote comment',

	'RANDOM_IMAGES'					=> 'Random images',
	'RATE_IMAGE'					=> 'Rate the image',
	'RATES_COUNT'					=> 'Number of ratings',
	'RATING'						=> 'Rating',
	'RATING_STRINGS'				=> array(
		0	=> 'not rated',
		1	=> '%2$s (1 rating)',
		2	=> '%2$s (%1$s ratings)',
	),
	'RATING_STRINGS_USER'			=> array(
		1	=> '%2$s (1 rating, your rating: %3$s)',
		2	=> '%2$s (%1$s ratings, your rating: %3$s)',
	),
	'RATING_SUCCESSFUL'				=> 'The image has been rated successfully.',
	'READ_REPORT'					=> 'Read report',
	'RECENT_COMMENTS'				=> 'Recent comments',
	'RECENT_IMAGES'					=> 'Recent Images',
	'REPORT_IMAGE'					=> 'Report image',
	'RETURN_ALBUM'					=> '%sReturn to the album last visited%s',
	'ROTATE_IMAGE'					=> 'Rotate image',
	'ROTATE_LEFT'					=> '90° left',
	'ROTATE_NONE'					=> 'none',
	'ROTATE_RIGHT'					=> '90° right',
	'ROTATE_UPSIDEDOWN'				=> '180° upside-down',

	'SEARCH_ALBUM'					=> 'Search this album…',
	'SEARCH_ALBUMS'					=> 'Search in albums',
	'SEARCH_ALBUMS_EXPLAIN'			=> 'Select the album or albums you wish to search in. Subalbums are searched automatically if you do not disable “search subalbums“ below.',
	'SEARCH_COMMENTS'				=> 'Comments only',
	'SEARCH_CONTEST'				=> 'Contest winners',
	'SEARCH_IMAGE_COMMENTS'			=> 'Imagenames, descriptions and comments',
	'SEARCH_IMAGE_VALUES'			=> 'Imagenames and descriptions only',
	'SEARCH_IMAGENAME'				=> 'Imagenames only',
	'SEARCH_RANDOM'					=> 'Random images',
	'SEARCH_RECENT'					=> 'Recent images',
	'SEARCH_RECENT_COMMENTS'		=> 'Recent comments',
	'SEARCH_SUBALBUMS'				=> 'Search subalbums',
	'SEARCH_TOPRATED'				=> 'Top rated images',
	'SEARCH_USER_IMAGES'			=> 'Search user’s images',
	'SEARCH_USER_IMAGES_OF'			=> 'Images of %s',
	'SELECT_ALBUM'					=> 'Select an album',
	'SHOW_PERSONAL_ALBUM_OF'		=> 'Show personal album of %s',
	'SLIDE_SHOW'					=> 'Slideshow',
	'SLIDE_SHOW_HIGHSLIDE'			=> 'To start the slideshow, click on one of the image-names and than click on the “play“-icon:',
	'SLIDE_SHOW_LYTEBOX'			=> 'To start the slideshow, click on one of the image-names:',
	'SLIDE_SHOW_SHADOWBOX'			=> 'To start the slideshow, click on one of the image-names:',
	'SORT_ASCENDING'				=> 'Ascending',
	'SORT_DEFAULT'					=> 'Default',
	'SORT_DESCENDING'				=> 'Descending',
	'STATUS'						=> 'Status',
	'SUBALBUMS'						=> 'Subalbums',
	'SUBALBUM'						=> 'Subalbum',

	'THUMBNAIL_SIZE'				=> 'Thumbnail size (pixels)',
	'TOTAL_COMMENTS_SPRINTF'		=> array(
		0	=> 'Total comments <strong>0</strong>',
		1	=> 'Total comments <strong>%d</strong>',
		2	=> 'Total comments <strong>%d</strong>',
	),
	'TOTAL_IMAGES'					=> 'Total images',
	'TOTAL_PEGAS_SHORT_SPRINTF'		=> array(
		0	=> '0 personal galleries',
		1	=> '%d personal gallery',
		2	=> '%d personal galleries',
	),
	'TOTAL_PEGAS_SPRINTF'		=> array(
		0	=> 'Total personal galleries <strong>0</strong>',
		1	=> 'Total personal galleries <strong>%d</strong>',
		2	=> 'Total personal galleries <strong>%d</strong>',
	),

	'UNLOCK_IMAGE'					=> 'Unlock image',
	'UNWATCH_ALBUM'					=> 'Unsubscribe album',
	'UNWATCH_IMAGE'					=> 'Unsubscribe image',
	'UNWATCH_PEGAS'					=> 'Do not subscribe to new personal galleries',
	'UNWATCHED_ALBUM'				=> 'You are no longer informed about new images in this album.',
	'UNWATCHED_ALBUMS'				=> 'You are no longer informed about new images in these albums.',
	'UNWATCHED_IMAGE'				=> 'You are no longer informed about new comments on this image.',
	'UNWATCHED_IMAGES'				=> 'You are no longer informed about new comments on these images.',
	'UNWATCHED_PEGAS'				=> 'You are no longer automatically subscribed to new personal galleries.',
	'UPLOAD_ERROR'					=> 'While uploading “%1$s“ the following error occurred:<br />&raquo; %2$s',
	'UPLOAD_IMAGE'					=> 'Upload Image',
	'UPLOAD_IMAGE_SIZE_TOO_BIG'		=> 'Your image dimension size is too large',
	'UPLOAD_NO_FILE'				=> 'You must enter your path and filename',
	'UPLOADED_BY_USER'				=> 'Uploaded by',
	'UPLOADED_ON_DATE'				=> 'Uploaded',
	'USE_SAME_NAME'					=> 'Use the same image name and description for all images.',
	'USE_NUM'						=> 'Add {NUM} for numbers. Start counting at:',
	'USER_REACHED_QUOTA'			=> array(
		0	=> 'You are not allowed to upload <strong>any</strong> images.<br />Please contact the administrator for more information.',
		1	=> 'You are not allowed to upload more than <strong>1</strong> image.<br />Please contact the administrator for more information.',
		2	=> 'You are not allowed to upload more than <strong>%s</strong> images.<br />Please contact the administrator for more information.',
	),
	'USER_REACHED_QUOTA_SHORT'		=> array(
		0	=> 'You are not allowed to upload <strong>any</strong> images.',
		1	=> 'You are not allowed to upload more than <strong>1</strong> image.',
		2	=> 'You are not allowed to upload more than <strong>%s</strong> images.',
	),
	'USERNAME_BEGINS_WITH'			=> 'Username begins with',
	'USERS_PERSONAL_ALBUMS'			=> 'Users Personal Albums',

	'VIEW_ALBUM'					=> 'View album',
	'VIEW_ALBUM_IMAGES'				=> array(
		1	=> '1 image',
		2	=> '%s images',
	),
	'VIEW_IMAGE'					=> 'View image',
	'VIEW_IMAGE_COMMENTS'			=> array(
		1	=> '1 comment',
		2	=> '%s comments',
	),
	'VIEW_LATEST_IMAGE'				=> 'View the latest image',
	'VIEW_SEARCH_RECENT'			=> 'View recent images',
	'VIEW_SEARCH_RANDOM'			=> 'View random images',
	'VIEW_SEARCH_COMMENTED'			=> 'View recent comments',
	'VIEW_SEARCH_CONTESTS'			=> 'View contest winners',
	'VIEW_SEARCH_TOPRATED'			=> 'View top rated images',
	'VIEW_SEARCH_SELF'				=> 'View your images',
	'VIEWING_ALBUM'					=> 'Viewing album %s',
	'VIEWING_IMAGE'					=> 'Viewing image in album %s',

	'WATCH_ALBUM'					=> 'Subscribe album',
	'WATCH_IMAGE'					=> 'Subscribe image',
	'WATCH_PEGAS'					=> 'Subscribe to new personal galleries',
	'WATCHING_ALBUM'				=> 'You are now informed about new images in this album.',
	'WATCHING_IMAGE'				=> 'You are now informed about new comments on this image.',
	'WATCHING_PEGAS'				=> 'You are now automatically subscribed to new personal galleries.',

	'YOUR_COMMENT'					=> 'Your comment',
	'YOUR_PERSONAL_ALBUM'			=> 'Your Personal Album',
	'YOUR_RATING'					=> 'Your rating',

	'IMAGES_MOVED'					=> array(
		1	=>	'Image moved',
		2	=> 	'%s images moved',
	),
));
